before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: cmd/awslim/main.go
    binary: awslim
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
      - -X github.com/fujiwara/awslim.Version={{.Version}}
    tags:
      - osusergo
      - netgo
    goos:
      - linux
      - darwin
      #- windows
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
