package main

import (
	"fmt"
	"log"
	"os"
	"reflect"
	"strings"
)

//go:generate go run ../aws-sdk-client-gen-gen/main.go
//go:generate go get ./...

func main() {
	generateAll()
}

func gen(pkgName string, clientType reflect.Type, genNames []string) error {
	log.Printf("generating %s_gen.go", pkgName)
	buf := &strings.Builder{}
	fmt.Fprintln(buf, "// Code generated by cmd/aws-sdk-client-gen/main.go; DO NOT EDIT.")
	fmt.Fprintln(buf, "package sdkclient")
	fmt.Fprintln(buf)
	fmt.Fprintf(buf, `import (
		"context"
		"encoding/json"
		"fmt"
		"github.com/aws/aws-sdk-go-v2/service/%s"
	)
	`, pkgName)
	var methodNames []string
	for i := 0; i < clientType.NumMethod(); i++ {
		method := clientType.Method(i)
		if len(genNames) > 0 && !contains(genNames, method.Name) {
			continue
		}
		params := make([]string, 0)
		for j := 0; j < method.Type.NumIn(); j++ {
			params = append(params, method.Type.In(j).String())
		}
		if len(params) <= 1 {
			log.Printf("no params func %s", method.Name)
			continue
		}
		methodNames = append(methodNames, method.Name)
		log.Printf("generating %s_%s", pkgName, method.Name)
		fmt.Fprintf(buf, `func %s_%s(ctx context.Context, b json.RawMessage) (any, error) {
			svc := %s.NewFromConfig(awsCfg)
			var in %s
			if err := json.Unmarshal(b, &in); err != nil {
				return nil, fmt.Errorf("failed to unmarshal request: %%w", err)
			}
			if out, err := svc.%s(ctx, &in); err != nil {
				return nil, fmt.Errorf("failed to call %s: %%w", err)
			} else {
				return out, nil
			}
		}
		`,
			pkgName,
			method.Name,
			pkgName,
			strings.TrimPrefix(params[2], "*"), // (receiver, context.Context, *Request, ...)
			method.Name,
			method.Name,
		)
		fmt.Fprintln(buf)
	}
	fmt.Fprintln(buf, `func init() {`)
	for _, name := range methodNames {
		fmt.Fprintf(buf, `clientMethods["%s_%s"] = %s_%s
		`, pkgName, name, pkgName, name)
	}
	fmt.Fprintln(buf, "}")
	f, err := os.OpenFile(pkgName+"_gen.go", os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()
	if _, err := f.WriteString(buf.String()); err != nil {
		return err
	}
	log.Printf("generated %s_gen.go", pkgName)
	return nil
}

func contains(ss []string, s string) bool {
	for _, v := range ss {
		if v == s {
			return true
		}
	}
	return false
}
