package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"strings"
	"text/template"

	"github.com/goccy/go-yaml"
)

const sdkServicePrefix = "github.com/aws/aws-sdk-go-v2/service/"

const templateStr = `// Code generated by cmd/awslim-gen-gen/main.go; DO NOT EDIT.
package main

import (
	"reflect"
{{ range $key, $value := .Services }}
	"github.com/aws/aws-sdk-go-v2/service/{{ $key }}"
{{- end }}
)

func generateAll() {
	var err error
{{ range $key, $value := .Services }}
{{- if eq (len $value) 0 }}
	err = gen("{{ $key }}", reflect.TypeOf({{ $key }}.New({{ $key }}.Options{})), nil)
{{- else }}
	err = gen("{{ $key }}", reflect.TypeOf({{ $key }}.New({{ $key }}.Options{})), {{ printf "%#v" $value }})
{{- end }}
	if err != nil {
		panic("failed to generate {{ $key }}" + err.Error())
	}
{{ end }}
}
`

// GenerateConfig is the configuration of gen.yaml.
// Keys of Services are service names, optionally with a version query
// for go get (e.g. "s3@v1.100.0").
type GenerateConfig struct {
	Services map[string][]string `json:"services"`
}

// ServiceConfig is the resolved configuration for generating code.
type ServiceConfig struct {
	// Services maps a service name to method names (nil means all methods).
	Services map[string][]string
	// Versions maps a service name to a version query for go get.
	Versions map[string]string
}

func parseServiceKey(key string) (name, version string, err error) {
	name, version, found := strings.Cut(strings.TrimSpace(key), "@")
	name = strings.TrimSpace(name)
	version = strings.TrimSpace(version)
	if name == "" {
		return "", "", fmt.Errorf("empty service name in %q", key)
	}
	if found && version == "" {
		return "", "", fmt.Errorf("empty version in %q", key)
	}
	return name, version, nil
}

func resolveConfig(cfg GenerateConfig) (*ServiceConfig, error) {
	sc := &ServiceConfig{
		Services: make(map[string][]string, len(cfg.Services)),
		Versions: make(map[string]string),
	}
	for key, methods := range cfg.Services {
		name, version, err := parseServiceKey(key)
		if err != nil {
			return nil, err
		}
		if _, exists := sc.Services[name]; exists {
			return nil, fmt.Errorf("service %s is specified more than once", name)
		}
		sc.Services[name] = methods
		if version != "" {
			sc.Versions[name] = version
		}
	}
	return sc, nil
}

func configFromEnv(e string) GenerateConfig {
	cfg := GenerateConfig{Services: map[string][]string{}}
	for service := range strings.SplitSeq(e, ",") {
		if strings.TrimSpace(service) == "" {
			continue
		}
		cfg.Services[service] = nil
	}
	return cfg
}

func configFromYAML(r io.Reader) (GenerateConfig, error) {
	cfg := GenerateConfig{}
	if err := yaml.NewDecoder(r).Decode(&cfg); err != nil {
		return cfg, err
	}
	return cfg, nil
}

// goGetArgs returns arguments for go get to pin the service module versions.
func goGetArgs(versions map[string]string) []string {
	if len(versions) == 0 {
		return nil
	}
	args := []string{"get"}
	for name, version := range versions {
		args = append(args, sdkServicePrefix+name+"@"+version)
	}
	return args
}

func main() {
	log.Println("generating gen.go")

	var cfg GenerateConfig
	if e := os.Getenv("AWSLIM_GEN"); e != "" {
		log.Printf("AWSLIM_GEN is set, generating services: %s", e)
		cfg = configFromEnv(e)
	} else {
		log.Printf("AWSLIM_GEN is not set, reading gen.yaml")
		f, err := os.Open("../../gen.yaml")
		if err != nil {
			log.Fatalf("failed to open gen.yaml: %v", err)
		}
		defer f.Close()
		cfg, err = configFromYAML(f)
		if err != nil {
			log.Fatalf("failed to decode gen.yaml: %v", err)
		}
	}
	sc, err := resolveConfig(cfg)
	if err != nil {
		log.Fatalf("invalid configuration: %v", err)
	}

	tmpl, err := template.New("gen").Parse(templateStr)
	if err != nil {
		log.Fatalf("failed to parse template: %v", err)
	}
	buf := &bytes.Buffer{}
	if err := tmpl.Execute(buf, sc); err != nil {
		log.Fatalf("failed to execute template: %v", err)
	}

	if err := os.WriteFile("gen.go", buf.Bytes(), 0644); err != nil {
		log.Fatalf("failed to write gen.go: %v", err)
	}
	log.Println("generated gen.go")

	if args := goGetArgs(sc.Versions); args != nil {
		log.Printf("pinning service versions: go %s", strings.Join(args, " "))
		cmd := exec.Command("go", args...)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			log.Fatalf("failed to pin service versions: %v", err)
		}
	}
}
